"""Adicionar campos CNPJ, endereço e logo à tabela Empresa

Revision ID: 1b1c01292907
Revises: 634fc0ed31cd
Create Date: 2025-10-27 00:00:56.703200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b1c01292907'
down_revision = '634fc0ed31cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('empresa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cnpj', sa.String(length=18), nullable=True))
        batch_op.add_column(sa.Column('cep', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('cidade', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('pais', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('logo_filename', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('empresa', schema=None) as batch_op:
        batch_op.drop_column('logo_filename')
        batch_op.drop_column('pais')
        batch_op.drop_column('cidade')
        batch_op.drop_column('cep')
        batch_op.drop_column('cnpj')

    # ### end Alembic commands ###
