"""Adicionar suporte para ordens não programadas com rastreamento detalhado de execução

Revision ID: 277245cefdcd
Revises: 1b1c01292907
Create Date: 2025-10-27 00:14:27.012721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '277245cefdcd'
down_revision = '1b1c01292907'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ordem_execucao', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo_ordem', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('setor_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('area_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('equipamento_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('servico_solicitado', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('tempo_previsto', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('data_hora_inicio', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('data_hora_fim', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('servico_executado', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('diagnostico_falha', sa.Text(), nullable=True))
        batch_op.alter_column('plano_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_ordem_execucao_area_id'), ['area_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ordem_execucao_equipamento_id'), ['equipamento_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ordem_execucao_setor_id'), ['setor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ordem_execucao_tipo_ordem'), ['tipo_ordem'], unique=False)
        batch_op.create_foreign_key(None, 'equipamento', ['equipamento_id'], ['id'])
        batch_op.create_foreign_key(None, 'area', ['area_id'], ['id'])
        batch_op.create_foreign_key(None, 'setor', ['setor_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ordem_execucao', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_ordem_execucao_tipo_ordem'))
        batch_op.drop_index(batch_op.f('ix_ordem_execucao_setor_id'))
        batch_op.drop_index(batch_op.f('ix_ordem_execucao_equipamento_id'))
        batch_op.drop_index(batch_op.f('ix_ordem_execucao_area_id'))
        batch_op.alter_column('plano_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('diagnostico_falha')
        batch_op.drop_column('servico_executado')
        batch_op.drop_column('data_hora_fim')
        batch_op.drop_column('data_hora_inicio')
        batch_op.drop_column('tempo_previsto')
        batch_op.drop_column('servico_solicitado')
        batch_op.drop_column('equipamento_id')
        batch_op.drop_column('area_id')
        batch_op.drop_column('setor_id')
        batch_op.drop_column('tipo_ordem')

    # ### end Alembic commands ###
