"""Adiciona a tabela Componente, Criticidade e indices de otimizacao

Revision ID: 634fc0ed31cd
Revises: 
Create Date: 2025-10-26 18:41:46.381398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '634fc0ed31cd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('area', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_area_setor_id'), ['setor_id'], unique=False)

    with op.batch_alter_table('conjunto', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conjunto_area_id'), ['area_id'], unique=False)

    with op.batch_alter_table('equipamento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('criticidade', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('valor_aquisicao', sa.Float(), nullable=True))
        batch_op.create_index(batch_op.f('ix_equipamento_codigo'), ['codigo'], unique=False)
        batch_op.create_index(batch_op.f('ix_equipamento_subconjunto_id'), ['subconjunto_id'], unique=False)

    with op.batch_alter_table('item_inspecao', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_item_inspecao_plano_id'), ['plano_id'], unique=False)
        batch_op.drop_column('observacao')
        batch_op.drop_column('outros')
        batch_op.drop_column('qtde_executantes')
        batch_op.drop_column('tempo_necessario')
        batch_op.drop_column('resultado')
        batch_op.drop_column('solucao')
        batch_op.drop_column('falha')
        batch_op.drop_column('materiais')
        batch_op.drop_column('valor_atual')

    with op.batch_alter_table('item_inspecao_apontado', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_item_inspecao_apontado_item_inspecao_id'), ['item_inspecao_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_item_inspecao_apontado_ordem_id'), ['ordem_id'], unique=False)

    with op.batch_alter_table('ordem_execucao', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ordem_execucao_data_programada'), ['data_programada'], unique=False)
        batch_op.create_index(batch_op.f('ix_ordem_execucao_executante_id'), ['executante_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ordem_execucao_plano_id'), ['plano_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ordem_execucao_status'), ['status'], unique=False)

    with op.batch_alter_table('plano_inspecao', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plano_inspecao_equipamento_id'), ['equipamento_id'], unique=False)

    with op.batch_alter_table('setor', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_setor_empresa_id'), ['empresa_id'], unique=False)

    with op.batch_alter_table('subconjunto', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subconjunto_conjunto_id'), ['conjunto_id'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.Text(),
               existing_nullable=False)
        batch_op.alter_column('funcao',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('perfil_acesso',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'executante'::character varying"))
        batch_op.drop_constraint(batch_op.f('user_matricula_unique'), type_='unique')
        batch_op.create_index(batch_op.f('ix_user_matricula'), ['matricula'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_perfil_acesso'), ['perfil_acesso'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_perfil_acesso'))
        batch_op.drop_index(batch_op.f('ix_user_matricula'))
        batch_op.create_unique_constraint(batch_op.f('user_matricula_unique'), ['matricula'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('perfil_acesso',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'executante'::character varying"))
        batch_op.alter_column('funcao',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('password_hash',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)

    with op.batch_alter_table('subconjunto', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subconjunto_conjunto_id'))

    with op.batch_alter_table('setor', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_setor_empresa_id'))

    with op.batch_alter_table('plano_inspecao', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plano_inspecao_equipamento_id'))

    with op.batch_alter_table('ordem_execucao', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ordem_execucao_status'))
        batch_op.drop_index(batch_op.f('ix_ordem_execucao_plano_id'))
        batch_op.drop_index(batch_op.f('ix_ordem_execucao_executante_id'))
        batch_op.drop_index(batch_op.f('ix_ordem_execucao_data_programada'))

    with op.batch_alter_table('item_inspecao_apontado', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_item_inspecao_apontado_ordem_id'))
        batch_op.drop_index(batch_op.f('ix_item_inspecao_apontado_item_inspecao_id'))

    with op.batch_alter_table('item_inspecao', schema=None) as batch_op:
        batch_op.add_column(sa.Column('valor_atual', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('materiais', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('falha', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('solucao', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('resultado', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('tempo_necessario', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('qtde_executantes', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('outros', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('observacao', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_index(batch_op.f('ix_item_inspecao_plano_id'))

    with op.batch_alter_table('equipamento', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_equipamento_subconjunto_id'))
        batch_op.drop_index(batch_op.f('ix_equipamento_codigo'))
        batch_op.drop_column('valor_aquisicao')
        batch_op.drop_column('criticidade')

    with op.batch_alter_table('conjunto', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conjunto_area_id'))

    with op.batch_alter_table('area', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_area_setor_id'))

    # ### end Alembic commands ###
